object Versions {
    const val gradlePlugin = "7.3.1"
    const val kotlin = "1.7.10"
    const val compose = "1.3.1"
    const val androidCore = "1.9.0"
    const val activityCompose = "1.4.0"
    const val lifecycleRuntime = "2.5.1"
    const val jUnit = "4.13.2"
    const val androidJUnit = "1.1.3"
    const val espresso = "3.4.0"
    const val kotlinCoroutines = "1.6.1"
    const val koin = "3.3.0"
    const val koinAndroid = "3.3.1"
    const val retrofit = "2.9.0"
    const val retrofitLog = "4.9.3"
    const val okhttp = "4.9.3"
    const val timber = "4.7.1"
    const val navigationFragment = "2.5.3"
    const val lottie = "5.0.3"
    const val lottieCompose = "5.0.3"
    const val dataStore = "1.0.0"
    const val pagerCompose = "0.24.5-alpha"
    const val room = "2.4.2"
    const val daggerHilt = "2.42"
    const val daggerHiltX = "1.0.0"
}